"""empty message

Revision ID: 21073b34125a
Revises: 
Create Date: 2020-06-20 15:10:16.923462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21073b34125a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_record_email'), 'record', ['email'], unique=True)
    op.create_index(op.f('ix_record_name'), 'record', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_name'), table_name='record')
    op.drop_index(op.f('ix_record_email'), table_name='record')
    op.drop_table('record')
    # ### end Alembic commands ###
