"""empty message

Revision ID: 64d1a01896bb
Revises: 
Create Date: 2020-06-19 17:09:30.274590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d1a01896bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('ref', sa.String(length=100), nullable=True),
    sa.Column('portfolio', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=True),
    sa.Column('yoc', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_asset_address'), 'asset', ['address'], unique=False)
    op.create_index(op.f('ix_asset_city'), 'asset', ['city'], unique=False)
    op.create_index(op.f('ix_asset_portfolio'), 'asset', ['portfolio'], unique=False)
    op.create_index(op.f('ix_asset_ref'), 'asset', ['ref'], unique=False)
    op.create_index(op.f('ix_asset_yoc'), 'asset', ['yoc'], unique=False)
    op.create_index(op.f('ix_asset_zipcode'), 'asset', ['zipcode'], unique=False)
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_id'), 'file', ['id'], unique=False)
    op.create_index(op.f('ix_file_status'), 'file', ['status'], unique=False)
    op.create_table('unit',
    sa.Column('id', sa.String(length=100), autoincrement=False, nullable=False),
    sa.Column('ref', sa.String(length=100), nullable=True),
    sa.Column('asset_id', sa.String(length=100), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('is_rented', sa.Boolean(), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('tenant', sa.String(length=100), nullable=True),
    sa.Column('lease_start', sa.DateTime(), nullable=True),
    sa.Column('lease_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_unit_is_rented'), 'unit', ['is_rented'], unique=False)
    op.create_index(op.f('ix_unit_ref'), 'unit', ['ref'], unique=False)
    op.create_index(op.f('ix_unit_rent'), 'unit', ['rent'], unique=False)
    op.create_index(op.f('ix_unit_size'), 'unit', ['size'], unique=False)
    op.create_index(op.f('ix_unit_tenant'), 'unit', ['tenant'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_tenant'), table_name='unit')
    op.drop_index(op.f('ix_unit_size'), table_name='unit')
    op.drop_index(op.f('ix_unit_rent'), table_name='unit')
    op.drop_index(op.f('ix_unit_ref'), table_name='unit')
    op.drop_index(op.f('ix_unit_is_rented'), table_name='unit')
    op.drop_table('unit')
    op.drop_index(op.f('ix_file_status'), table_name='file')
    op.drop_index(op.f('ix_file_id'), table_name='file')
    op.drop_table('file')
    op.drop_index(op.f('ix_asset_zipcode'), table_name='asset')
    op.drop_index(op.f('ix_asset_yoc'), table_name='asset')
    op.drop_index(op.f('ix_asset_ref'), table_name='asset')
    op.drop_index(op.f('ix_asset_portfolio'), table_name='asset')
    op.drop_index(op.f('ix_asset_city'), table_name='asset')
    op.drop_index(op.f('ix_asset_address'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
